# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1497df5ee4a87f287c72d2c648b639a2"
name = "srpn-test-app"
handle = "srpn-test-app-1"
application_url = "https://boots-perl-edited-architect.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "srpn-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://boots-perl-edited-architect.trycloudflare.com/auth/callback",
  "https://boots-perl-edited-architect.trycloudflare.com/auth/shopify/callback",
  "https://boots-perl-edited-architect.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
